var showAllTenantButton = document.getElementById("allTenantReport");
var showAllPropertyButton = document.getElementById("allPropertyReport");

var leftTenantReport = document.getElementById("tenant-report-container");
var rightPropertyReport = document.getElementById("property-report-container");

///////////////////js ajax for listing tenants
$(document).ready(function () {
    // Function to load all properties
    function loadAllProperties() {
        $.ajax({
            url: 'tenantReport.php', // Change the URL to your PHP script
            type: 'GET',
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by tenantReport.php
                $("#tenant-data-table").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Function to search for specific tenants
    function searchTenantsByName(searchTerm) {
        $.ajax({
            url: 'tenantReport.php', // Change the URL to your PHP script
            type: 'GET',
            data: { search: searchTerm }, // Pass the search term as a parameter
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by tenantReport.php
                $("#tenant-data-table").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Click event for "Generate All Tenants" button
    $("#generateAllProperties").click(function () {
        loadAllProperties();
    });

    // Click event for "Generate search Tenants" button
    $("#generateSearchReport").click(function () {
        var searchTerm = $("#tenantSearchbar").val();
        searchTenantsByName(searchTerm);
    });
});

/////////////////////////////js for listing properties
// script.js
$(document).ready(function () {
    // Function to load all properties
    function loadAllProperties() {
        $.ajax({
            url: 'propertyReport.php', // Change the URL to your PHP script
            type: 'GET',
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by propertyReport.php
                $("#property-report-text-container").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Function to search for specific properties by name
    function searchPropertiesByName(searchTerm) {
        $.ajax({
            url: 'propertyReport.php', // Change the URL to your PHP script
            type: 'GET',
            data: { search: searchTerm }, // Pass the search term as a parameter
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by propertyReport.php
                $("#property-report-text-container").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Click event for "Generate Report" button
    $("#generatePropertyReport").click(function () {
        var searchTerm = $("#propertySearchbar").val();
        searchPropertiesByName(searchTerm);
    });

    // Click event for "List All Properties" button
    $("#allPropertyReport").click(function () {
        loadAllProperties();
    });
});


/////////////////////////////js for digs criteia report
// script.js
$(document).ready(function () {
    // Function to load all properties
    function loadPropertiesByCriteria(criteriaTerm, searchTerm) {
        $.ajax({
            url: 'criteriaReport.php', // Change the URL to your PHP script
            type: 'GET',
            data: { criteria: criteriaTerm, search: searchTerm},
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by propertyReport.php
                $("#criteria-report-text-container").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Click event for "Generate Report" button
    $("#generateCriteriaReport").click(function () {
        if ($("#criteria-dropdown").val() != 'null') {
            let criteria = $("#criteria-dropdown").val(); 
            let searchTerm = $("#criteria-searchbar").val();
            loadPropertiesByCriteria(criteria, searchTerm);     
        }
    });

});

const selectPlaceholder = document.getElementById('select-placeholder');
const criteriaDropdown = document.getElementById('criteria-dropdown');

// listen for criteria drop down button
document.getElementById('chooseCriteria').addEventListener('click', function(event) {
    selectPlaceholder.style.display = 'none';
    criteriaDropdown.style.display = 'block';
    console.log("clicked criteria btton");
});


////////////////////------- Google charts -------/////////////////////

$(document).ready(function () {
    // Function to load all properties
    function loadChart(chartType) {
        $.ajax({
            url: 'chartReports.php', // Change the URL to your PHP script
            type: 'GET',
            data: { chart: chartType },
            success: function (data) {
                google.charts.load("current", {packages:['corechart']});
                google.charts.setOnLoadCallback(drawChart);
                function drawChart() {
                    console.log(data);
                    console.log(typeof data);
                    
                    const dataArray = JSON.parse(data);

                    console.log(dataArray);
                    
                // for (let index = 0; index < data.length; index++) {
                //     const el = data[index];
                //     console.log(el);
                    
                // }
                // data.forEach(element => {
                //     console.log(element);
                // });
                // var dataArray = google.visualization.arrayToDataTable([
                //     ["Element", "Density", { role: "style" } ],
                //     ["Copper", 8.94, "#b87333"],
                //     ["Silver", 10.49, "silver"],
                //     ["Gold", 19.30, "gold"],
                //     ["Platinum", 21.45, "color: #e5e4e2"]
                // ]);

                // var view = new google.visualization.DataView(data);
                // view.setColumns([0, 1,
                //                 { calc: "stringify",
                //                     sourceColumn: 1,
                //                     type: "string",
                //                     role: "annotation" },
                //                 2]);

                // var options = {
                //     title: "Density of Precious Metals, in g/cm^3",
                //     width: 600,
                //     height: 400,
                //     bar: {groupWidth: "95%"},
                //     legend: { position: "none" },
                // };
                // var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));
                // chart.draw(view, options);
            }
            },  
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }
    

    // Click event for "Generate Report" button
    $("#generateChartReport").click(function () {
        let chartOption = $("#chart-dropdown").val(); // Get the selected value
        console.log(chartOption);
        loadChart(chartOption);
    });
});



const chartSelectPlaceholder = document.getElementById('chart-select-placeholder');
const chartDropdown = document.getElementById('chart-dropdown');

// listen for criteria drop down button
document.getElementById('chooseChart').addEventListener('click', function(event) {
    chartSelectPlaceholder.style.display = 'none';
    chartDropdown.style.display = 'block';
    console.log("clicked criteria btton");
});