var showAllTenantButton = document.getElementById("allTenantReport");
var showAllPropertyButton = document.getElementById("allPropertyReport");

var leftTenantReport = document.getElementById("tenant-report-container");
var rightPropertyReport = document.getElementById("property-report-container");

///////////////////js ajax for listing tenants
$(document).ready(function () {
    // Function to load all properties
    function loadAllProperties() {
        $.ajax({
            url: 'tenantReport.php', // Change the URL to your PHP script
            type: 'GET',
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by tenantReport.php
                $("#tenant-data-table").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Function to search for specific tenants
    function searchTenantsByName(searchTerm) {
        $.ajax({
            url: 'tenantReport.php', // Change the URL to your PHP script
            type: 'GET',
            data: { search: searchTerm }, // Pass the search term as a parameter
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by tenantReport.php
                $("#tenant-data-table").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Click event for "Generate All Tenants" button
    $("#generateAllProperties").click(function () {
        loadAllProperties();
    });

    // Click event for "Generate search Tenants" button
    $("#generateSearchReport").click(function () {
        var searchTerm = $("#tenantSearchbar").val();
        searchTenantsByName(searchTerm);
    });
});

/////////////////////////////js for listing properties
// script.js
$(document).ready(function () {
    // Function to load all properties
    function loadAllProperties() {
        $.ajax({
            url: 'propertyReport.php', // Change the URL to your PHP script
            type: 'GET',
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by propertyReport.php
                $("#property-report-text-container").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Function to search for specific properties by name
    function searchPropertiesByName(searchTerm) {
        $.ajax({
            url: 'propertyReport.php', // Change the URL to your PHP script
            type: 'GET',
            data: { search: searchTerm }, // Pass the search term as a parameter
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by propertyReport.php
                $("#property-report-text-container").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Click event for "Generate Report" button
    $("#generatePropertyReport").click(function () {
        var searchTerm = $("#propertySearchbar").val();
        searchPropertiesByName(searchTerm);
    });

    // Click event for "List All Properties" button
    $("#allPropertyReport").click(function () {
        loadAllProperties();
    });
});


/////////////////////////////js for digs criteia report
// script.js
$(document).ready(function () {
    // Function to load all properties
    function loadPropertiesByCriteria(searchTerm) {
        $.ajax({
            url: 'criteriaReport.php', // Change the URL to your PHP script
            type: 'GET',
            data: { search: searchTerm },
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by propertyReport.php
                $("#criteria-report-text-container").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Click event for "Generate Report" button
    $("#generateCriteriaReport").click(function () {
        let searchTerm = $("#criteria-dropdown").val(); // Get the selected value
        // console.log(searchTerm);
        loadPropertiesByCriteria(searchTerm);
    });

    // // Click event for "List All Properties" button
    // $("#allPropertyReport").click(function () {
    //     loadAllProperties();
    // });
});

const selectPlaceholder = document.getElementById('select-placeholder');
const criteriaDropdown = document.getElementById('criteria-dropdown');

// listen for criteria drop down button
document.getElementById('chooseCriteria').addEventListener('click', function(event) {
    selectPlaceholder.style.display = 'none';
    criteriaDropdown.style.display = 'block';
    console.log("clicked criteria btton");
});

// document.addEventListener('click', function(event) {
//     // var selectElement = document.getElementById('country');
//     if (selectPlaceholder.style.display === 'block' && !selectPlaceholder.contains(event.target)) {
//         // The select element is visible and the click event did not occur within it
//         // Execute your desired action here
//         console.log('User clicked off the drop down');
//         criteriaDropdown.style.display = 'none';
//         selectPlaceholder.style.display = 'block';
//     }
// });