var showAllTenantButton = document.getElementById("allTenantReport");
var showAllPropertyButton = document.getElementById("allPropertyReport");

var leftTenantReport = document.getElementById("tenant-report-container");
var rightPropertyReport = document.getElementById("property-report-container");

///////////////////js ajax for listing tenants
$(document).ready(function () {
    // Function to load all properties
    function loadAllProperties() {
        $.ajax({
            url: 'tenantReport.php', // Change the URL to your PHP script
            type: 'GET',
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by tenantReport.php
                $("#tenant-data-table").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Function to search for specific tenants
    function searchTenantsByName(searchTerm) {
        $.ajax({
            url: 'tenantReport.php', // Change the URL to your PHP script
            type: 'GET',
            data: { search: searchTerm }, // Pass the search term as a parameter
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by tenantReport.php
                $("#tenant-data-table").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Click event for "Generate All Tenants" button
    $("#generateAllProperties").click(function () {
        loadAllProperties();
    });

    // Click event for "Generate search Tenants" button
    $("#generateSearchReport").click(function () {
        var searchTerm = $("#tenantSearchbar").val();
        searchTenantsByName(searchTerm);
    });
});

/////////////////////////////js for listing properties
script.js
$(document).ready(function () {
    // Function to load all properties
    function loadAllProperties() {
        $.ajax({
            url: 'propertyReport.php', // Change the URL to your PHP script
            type: 'GET',
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by propertyReport.php
                $("#property-report-text-container").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Function to search for specific properties by name
    function searchPropertiesByName(searchTerm) {
        $.ajax({
            url: 'propertyReport.php', // Change the URL to your PHP script
            type: 'GET',
            data: { search: searchTerm }, // Pass the search term as a parameter
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by propertyReport.php
                $("#property-report-text-container").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Click event for "Generate Report" button
    $("#generatePropertyReport").click(function () {
        var searchTerm = $("#propertySearchbar").val();
        searchPropertiesByName(searchTerm);
    });

    // Click event for "List All Properties" button
    $("#allPropertyReport").click(function () {
        loadAllProperties();
    });
});


/////////////////////////////js for digs criteia report
script.js
$(document).ready(function () {
    // Function to load all properties
    function loadAllProperties() {
        $.ajax({
            url: 'criteriaReport.php', // Change the URL to your PHP script
            type: 'GET',
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by propertyReport.php
                $("#pcriteria-report-text-container").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Function to search for specific properties by name
    function searchPropertiesByName(searchTerm) {
        $.ajax({
            url: 'criteriaReport.php', // Change the URL to your PHP script
            type: 'GET',
            data: { search: searchTerm }, // Pass the search term as a parameter
            success: function (data) {
                // Assuming 'data' contains the HTML table rows generated by propertyReport.php
                $("#criteria-report-text-container").html(data);
            },
            error: function () {
                alert("An error occurred while fetching the report.");
            }
        });
    }

    // Click event for "Generate Report" button
    $("#generatePropertyReport").click(function () {
        var searchTerm = $("#propertySearchbar").val();
        searchPropertiesByName(searchTerm);
    });

    // Click event for "List All Properties" button
    $("#allPropertyReport").click(function () {
        loadAllProperties();
    });
});

